smoke tewst health workflok check

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -4,9 +4,55 @@ on:
   workflow_call:
 
 jobs:
-  working-job:
+  smoke:
     runs-on: ubuntu-latest
-
     steps:
-      - name : Echo Message
-        run : echo "Smoke testing is working successfully ✅"
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::949678235787:role/github-action-deploy-policy
+          aws-region: us-east-1
+
+      - name: Upload smoke_test.py on AWS
+        run: |
+          aws s3 cp smoke_test.py \
+          s3://949678235787-devops-scripts/smoke_test.py \
+          --region us-east-1
+
+      - name: Run smoke test on fleet
+        id: smoke
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{"commands":[
+              "aws s3 cp s3://949678235787-devops-scripts/smoke_test.py /tmp/smoke_test.py /tmpr/smoke_test.py"
+              "python3 /tmp/smoke_test.py"
+              ]}' 
+            
+            --query 'Command.CommandId' \
+            --output text \
+            --region us-east-1)
+          echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
+
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --output text
+
+            FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text)
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Smoke Test Failed on $FAILED instances" && \
+          exit 1
+
+          echo "ALL Instances Healthy ✅"
