smoke test health workflok check3

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -1,11 +1,12 @@
-name : Smoke testing 
+name: Smoke testing
 
 on:
-  workflow_call:
+  workflow_dispatch:
 
 jobs:
   smoke:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
 
@@ -14,26 +15,27 @@ jobs:
           role-to-assume: arn:aws:iam::949678235787:role/github-action-deploy-policy
           aws-region: us-east-1
 
-      - name: Upload smoke_test.py on AWS
+      - name: Upload smoke_test.py to S3
         run: |
-          aws s3 cp smoke_test.py \
-          s3://s3-lakhan-bucket/smoke_test.py \
-          --region us-east-1
+          aws s3 mb s3:///s3-lakhan-bucket --region us-east-1 2>/dev/null || true
+          aws s3 cp smoke_test.py s3://s3-lakhan-bucket/smoke_test.py --region us-east-1
 
-      - name: Run smoke test on fleet
+      - name: Run Smoke Test on Fleet
         id: smoke
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":[
-              "aws s3 cp s3://s3-lakhan-bucket/smoke_test.py /tmp/smoke_test.py",
-
-              "python3 /tmp/smoke_test.py || exit 1",
-              ]}' \
-            --query 'Command.CommandId' \
+            --parameters '{
+              "commands": [
+                "aws s3 cp s3://s3-lakhan-bucket/smoke_test.py /tmp/smoke_test.py",
+                "python3 /tmp/smoke_test.py || exit 1",
+                "rm -f /tmp/smoke_test.py"
+            ]}' \
+            --query "Command.CommandId" \
             --output text \
             --region us-east-1)
+
           echo "cmd_id=$CMD_ID" >> $GITHUB_OUTPUT
 
       - name: Show Results
@@ -46,15 +48,15 @@ jobs:
             --region us-east-1 \
             --output text
 
-            FAILED=$(aws ssm list-command-invocations \
+          FAILED=$(aws ssm list-command-invocations \
             --command-id "${{ steps.smoke.outputs.cmd_id }}" \
-            --details \
-            --region us-east-1 \
             --query "length(CommandInvocations[?Status=='Failed'])" \
-            --output text)
+            --output text \
+            --region us-east-1)
 
-          [ "$FAILED" -gt 0 ] && \
-          echo "::error::Smoke Test Failed on $FAILED instances" && \
-          exit 1
+          if [ "$FAILED" -gt 0 ]; then
+            echo "::error::Smoke Test Failed on $FAILED instance(s)"
+            exit 1
+          fi
 
-          echo "ALL Instances Healthy ✅"
+          echo "✅ Smoke Test Passed!"
