update2

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -1,42 +1,58 @@
-name: Test fleet
+name: Test Fleet health and Env Variables
 
 on:
   workflow_call:
 
+
 permissions:
-  contents: read
   id-token: write
+  contents: read
 
 jobs:
   test:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: aws-actions/configure-aws-credentials@v2
+      - uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::949678235787:role/github-action-deploy-policy
+          role-to-assume: arn:aws:iam::949678235787:role/github-action-deploy-plicy
           aws-region: us-east-1
 
-      - name: Print Private IPs
+      - name: Fleet Health Checks
+        id: health
         run: |
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
             --parameters '{"commands":[
-              "hostname -I"
-              "docker --version 2>/dev/null || echo Docker not installed"
-              "aws --version 2>/dev/null || echo AWS CLI not installed"
-              "mysql --version 2>/dev/null || echo MySQL not installed"
+              "hostname -I",
+              "docker --version 2>/dev/null  echo DOCKER NOT INSTALLED",
+              "aws --version 2>/dev/null  echo AWS CLI NOT INSTALLED",
+              "mysql --version 2>/dev/null || echo DOCKER NOT INSTALLED",
               "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
               ]}' \
-            --query 'Command.CommandId' \
-            --output text
-          )
-        
-          sleep 30
-
+            --query 'Command.CommandId' --output text \
+            --region us-east-1)
+          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
+      
+      
+      - name: Show Results
+        run:   
+          sleep 20
           aws ssm list-command-invocations \
-            --command-id "${{steps.help.outputs.CMD_ID}}" --details \
-            --region us-east-1 \
-            --query 'CommandInvocations[*].{Instance:InstanceId,IP:CommandPlugins[0].Output}' \
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --region us-east-1
+            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
             --output text
+          
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1
+            )
+
+          [ "$FAILED" -gt 0 ] && \
+          echo "::error::Health Check Failed on $FAILED instances" && \
+          exit 1
+
+          echo "ALL Instances Healthy ✅"
